[package]
name = "CyberRC"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
anyhow = "1.0.89"
chrono = "0.4.38"
clap = { version = "4.5.20", features = ["derive"] }
prost = "0.13.3"
prost-build = "0.13.3"
serialport = "4.5.1"

[build-dependencies]
prost-build = "0.13.3"
