"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class RCData(google.protobuf.message.Message):
    """Message definition for RC data"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AILERON_FIELD_NUMBER: builtins.int
    ELEVATOR_FIELD_NUMBER: builtins.int
    THROTTLE_FIELD_NUMBER: builtins.int
    RUDDER_FIELD_NUMBER: builtins.int
    ARM_FIELD_NUMBER: builtins.int
    MODE_FIELD_NUMBER: builtins.int
    Aileron: builtins.float
    Elevator: builtins.float
    Throttle: builtins.float
    Rudder: builtins.float
    Arm: builtins.int
    Mode: builtins.int
    def __init__(
        self,
        *,
        Aileron: builtins.float = ...,
        Elevator: builtins.float = ...,
        Throttle: builtins.float = ...,
        Rudder: builtins.float = ...,
        Arm: builtins.int = ...,
        Mode: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["Aileron", b"Aileron", "Arm", b"Arm", "Elevator", b"Elevator", "Mode", b"Mode", "Rudder", b"Rudder", "Throttle", b"Throttle"]) -> None: ...

global___RCData = RCData
