# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: RCData.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'RCData.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cRCData.proto\x12\x07\x63yberrc\"h\n\x06RCData\x12\x0f\n\x07\x41ileron\x18\x01 \x01(\x02\x12\x10\n\x08\x45levator\x18\x02 \x01(\x02\x12\x10\n\x08Throttle\x18\x03 \x01(\x02\x12\x0e\n\x06Rudder\x18\x04 \x01(\x02\x12\x0b\n\x03\x41rm\x18\x05 \x01(\x05\x12\x0c\n\x04Mode\x18\x06 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RCData_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RCDATA']._serialized_start=25
  _globals['_RCDATA']._serialized_end=129
# @@protoc_insertion_point(module_scope)
