name: Build and Test Firmware

on:
  push:
    paths:
      - "firmware/**" # Only trigger if files in the firmware directory change
  pull_request:
    paths:
      - "firmware/**" # Only trigger if files in the firmware directory change
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install tmate
        run: sudo apt-get install -y tmate

      - name: Start tmate session
        run: tmate -F

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install PlatformIO
        run: pip install platformio

      - name: Cache PlatformIO dependencies
        uses: actions/cache@v3
        with:
          path: ~/.platformio
          key: platformio-${{ runner.os }}-${{ hashFiles('firmware/platformio.ini') }}
          restore-keys: |
            platformio-${{ runner.os }}-

      - name: Get firmware deps
        run: pio pkg install
        working-directory: firmware

      - name: Clone ArduinoXInput_Teensy Repository
        run: |
          git clone https://github.com/dmadison/ArduinoXInput_Teensy.git /tmp/ArduinoXInput_Teensy

      - name: Replace Teensy Core Files
        run: |
          TEENSY_PATH="$HOME/.platformio/packages/framework-arduinoteensy/cores"
          echo "Replacing Teensy core directories..."
          rm -rf "$TEENSY_PATH/teensy3" "$TEENSY_PATH/teensy4"
          cp -r /tmp/ArduinoXInput_Teensy/teensy3 "$TEENSY_PATH/"
          cp -r /tmp/ArduinoXInput_Teensy/teensy4 "$TEENSY_PATH/"

      - name: Build firmware
        run: pio run
        working-directory: firmware

      - name: Run PlatformIO tests (if applicable)
        run: pio test
        working-directory: firmware
